SELECT COUNT(*) FROM expense;

INSERT INTO expense_category_mapping (state, raw_category_label, mapped_category, created_at)
VALUES
('', 'MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE PARLAMENTAR', 'OFFICE_MAINTENANCE', NOW()),
('', 'COMBUSTÍVEIS E LUBRIFICANTES', 'FUEL', NOW()),
('', 'PASSAGEM AÉREA', 'AIRFARE', NOW()),
('', 'LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES', 'VEHICLE_RENTAL', NOW()),
('', 'DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR', 'ADVERTISING', NOW()),
('', 'TELEFONIA', 'PHONE_INTERNET', NOW()),
('', 'SERVIÇOS POSTAIS', 'MAIL', NOW()),
('', 'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR', 'MEALS', NOW()),
('', 'HOSPEDAGEM', 'LODGING', NOW()),
('', 'CONSULTORIAS, PESQUISAS E TRABALHOS TÉCNICOS', 'CONSULTING', NOW());

SELECT description, COUNT(*) AS qtd
FROM expense
WHERE category = 'OTHER'
GROUP BY description
ORDER BY qtd DESC
LIMIT 50;

INSERT INTO expense_category_mapping (state, raw_category_label, mapped_category, created_at) VALUES
('', 'MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE PARLAMENTAR', 'OFFICE_MAINTENANCE', NOW()),
('', 'COMBUSTÍVEIS E LUBRIFICANTES', 'FUEL', NOW()),
('', 'COMBUSTÍVEIS E LUBRIFICANTES.', 'FUEL', NOW()),
('', 'PASSAGEM AÉREA', 'AIRFARE', NOW()),
('', 'PASSAGENS AÉREAS', 'AIRFARE', NOW()),
('', 'DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR', 'ADVERTISING', NOW()),
('', 'TELEFONIA', 'PHONE_INTERNET', NOW()),
('', 'SERVIÇOS POSTAIS', 'MAIL', NOW()),
('', 'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR', 'MEALS', NOW()),
('', 'HOSPEDAGEM', 'LODGING', NOW()),
('', 'HOSPEDAGEM, EXCETO DO PARLAMENTAR NO DISTRITO FEDERAL', 'LODGING', NOW()),
('', 'LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES', 'VEHICLE_RENTAL', NOW()),
('', 'LOCAÇÃO OU FRETAMENTO DE AERONAVES', 'VEHICLE_RENTAL', NOW()),
('', 'LOCAÇÃO OU FRETAMENTO DE EMBARCAÇÕES', 'VEHICLE_RENTAL', NOW()),
('', 'SERVIÇO DE TÁXI, PEDÁGIO E ESTACIONAMENTO', 'OTHER', NOW()),
('', 'PASSAGENS TERRESTRES, MARÍTIMAS OU FLUVIAIS', 'OTHER', NOW()),
('', 'CONSULTORIAS, PESQUISAS E TRABALHOS TÉCNICOS', 'CONSULTING', NOW()),
('', 'SERVIÇOS DE SEGURANÇA PRESTADOS POR EMPRESA ESPECIALIZADA', 'SECURITY', NOW()),
('', 'ASSINATURA DE PUBLICAÇÕES', 'OTHER', NOW()),
('', 'PARTICIPAÇÃO EM CURSO, PALESTRA OU EVENTO SIMILAR', 'TRAINING', NOW()),
('', 'COMPLEMENTAÇÃO DE AUXÍLIO-MORADIA', 'HOUSING_ALLOWANCE', NOW())
ON CONFLICT DO NOTHING;












  