SELECT COUNT(*) FROM expense;

INSERT INTO expense_category_mapping (state, raw_category_label, mapped_category, created_at)
VALUES
('', 'MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE PARLAMENTAR', 'OFFICE_MAINTENANCE', NOW()),
('', 'COMBUSTÍVEIS E LUBRIFICANTES', 'FUEL', NOW()),
('', 'PASSAGEM AÉREA', 'AIRFARE', NOW()),
('', 'LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES', 'VEHICLE_RENTAL', NOW()),
('', 'DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR', 'ADVERTISING', NOW()),
('', 'TELEFONIA', 'PHONE_INTERNET', NOW()),
('', 'SERVIÇOS POSTAIS', 'MAIL', NOW()),
('', 'FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR', 'MEALS', NOW()),
('', 'HOSPEDAGEM', 'LODGING', NOW()),
('', 'CONSULTORIAS, PESQUISAS E TRABALHOS TÉCNICOS', 'CONSULTING', NOW());